apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: awel07/api-server
          envFrom:
            - configMapRef:
                name: my-config
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001 
      nodePort: 30101